/** IPC / runtime message types for authentication. */
export const AUTH_STATE_CHANGED = 'AUTH_STATE_CHANGED' as const;
export const AUTH_SESSION_CLEARED = 'AUTH_SESSION_CLEARED' as const;
export const SYNC_AUTH_SESSION = 'SYNC_AUTH_SESSION' as const;
export const CLEAR_VERIFICATION_STATE = 'CLEAR_VERIFICATION_STATE' as const;

export const AUTH_IPC = {
  LOGIN: 'LOGIN',
  LOGIN_EMAIL: 'LOGIN_EMAIL',
  REGISTER_EMAIL: 'REGISTER_EMAIL',
  LOGOUT: 'LOGOUT',
  GET_AUTH_STATE: 'GET_AUTH_STATE',
  SYNC_AUTH_SESSION,
  CLEAR_VERIFICATION_STATE,
  AUTH_STATE_CHANGED,
  AUTH_SESSION_CLEARED,
} as const;
