#!/usr/bin/env bash
# =============================================================================
# scripts/issue-start.sh
# Kickoff a new issue: create git worktree + generate planning scaffolds.
#
# Usage:
#   ./scripts/issue-start.sh \
#     --issue <n> \
#     --milestone <m1|m2|...> \
#     --track <backend|frontend|fullstack|uiux|provider|devops|docs|qa|infra> \
#     [--slug <short-slug>] \
#     [--base <base-ref>]   # default: dev/P0.1
#
# Outputs (written to docs/implementation-plans/):
#   issue-<n>-spec-analysis.md   raw issue spec + context
#   issue-<n>-analysis.md        approach scaffold (filled by Claude)
#   issue-<n>-todos.md           todo checklist scaffold (filled by Claude)
# =============================================================================

set -euo pipefail

# ── Arg parsing ───────────────────────────────────────────────────────────────
ISSUE=""
MILESTONE=""
TRACK=""
SLUG=""
BASE="dev"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --issue)     ISSUE="$2";     shift 2 ;;
        --milestone) MILESTONE="$2"; shift 2 ;;
        --track)     TRACK="$2";     shift 2 ;;
        --slug)      SLUG="$2";      shift 2 ;;
        --base)      BASE="$2";      shift 2 ;;
        *) echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
done

# ── Validation ────────────────────────────────────────────────────────────────
if [[ -z "$ISSUE" || -z "$MILESTONE" || -z "$TRACK" ]]; then
    echo "ERROR: --issue, --milestone, and --track are required." >&2
    exit 1
fi

VALID_TRACKS="backend frontend fullstack uiux provider devops docs qa infra"
if ! echo "$VALID_TRACKS" | grep -qw "$TRACK"; then
    echo "ERROR: --track must be one of: $VALID_TRACKS" >&2
    exit 1
fi

# Strip leading # if provided as #5
ISSUE="${ISSUE#\#}"

# ── Fetch issue from GitHub ───────────────────────────────────────────────────
echo "Fetching issue #${ISSUE} from GitHub..."
ISSUE_JSON=$(gh issue view "$ISSUE" --json number,title,body,labels,milestone,state,url 2>/dev/null) || {
    echo "ERROR: Could not fetch issue #${ISSUE}. Is gh authenticated?" >&2
    exit 1
}

ISSUE_TITLE=$(echo "$ISSUE_JSON" | jq -r '.title')
ISSUE_BODY=$(echo "$ISSUE_JSON"  | jq -r '.body // "(no body)"')
ISSUE_URL=$(echo "$ISSUE_JSON"   | jq -r '.url')
ISSUE_MILESTONE=$(echo "$ISSUE_JSON" | jq -r '.milestone.title // "none"')
ISSUE_LABELS=$(echo "$ISSUE_JSON" | jq -r '[.labels[].name] | join(", ")')
ISSUE_STATE=$(echo "$ISSUE_JSON" | jq -r '.state')

# ── Derive slug and branch name ───────────────────────────────────────────────
if [[ -z "$SLUG" ]]; then
    # Auto-derive slug from issue title: lowercase, replace non-alphanum with -, truncate
    SLUG=$(echo "$ISSUE_TITLE" \
        | tr '[:upper:]' '[:lower:]' \
        | sed 's/[^a-z0-9]/-/g' \
        | sed 's/-\+/-/g' \
        | sed 's/^-//;s/-$//' \
        | cut -c1-30)
fi

BRANCH="fix/${MILESTONE}-${TRACK}-${SLUG}"
WT_DIR="worktrees/wt-${ISSUE}-${SLUG}"
PLAN_DIR="docs/implementation-plans"

echo ""
echo "Issue:     #${ISSUE} — ${ISSUE_TITLE}"
echo "Branch:    ${BRANCH}"
echo "Worktree:  ${WT_DIR}"
echo "Base:      ${BASE}"
echo ""

# ── Create git worktree ───────────────────────────────────────────────────────
if git worktree list | grep -q "${BRANCH}"; then
    echo "Worktree for branch '${BRANCH}' already exists. Skipping creation."
else
    echo "Creating worktree..."
    git worktree add "$WT_DIR" -b "$BRANCH" "$BASE"
    echo "Worktree created at: ${WT_DIR}"
fi

# ── Create plan dir in worktree ───────────────────────────────────────────────
mkdir -p "${WT_DIR}/${PLAN_DIR}"

# ── Generate spec-analysis.md ─────────────────────────────────────────────────
SPEC_FILE="${WT_DIR}/${PLAN_DIR}/issue-${ISSUE}-spec-analysis.md"
cat > "$SPEC_FILE" <<SPEC
# Issue #${ISSUE} — Spec Analysis

> Auto-generated by \`scripts/issue-start.sh\`
> Branch: \`${BRANCH}\`
> Worktree: \`${WT_DIR}\`
> Base: \`${BASE}\`

## GitHub Issue

- **URL**: ${ISSUE_URL}
- **Title**: ${ISSUE_TITLE}
- **Milestone**: ${ISSUE_MILESTONE}
- **Labels**: ${ISSUE_LABELS}
- **State**: ${ISSUE_STATE}

## Issue Body

${ISSUE_BODY}

## Context

- **Track**: ${TRACK}
- **Milestone**: ${MILESTONE}
- **Slug**: ${SLUG}
- **Date started**: $(date '+%Y-%m-%d')
SPEC

echo "Generated: ${SPEC_FILE}"

# ── Generate analysis.md scaffold ─────────────────────────────────────────────
ANALYSIS_FILE="${WT_DIR}/${PLAN_DIR}/issue-${ISSUE}-analysis.md"
cat > "$ANALYSIS_FILE" <<ANALYSIS
# Issue #${ISSUE} — Technical Analysis

> To be completed by Claude before implementation begins.

## Files to Modify

<!-- List every file that will be touched and why -->

| File | Change Type | Reason |
|---|---|---|
| | | |

## Approach

<!-- Step-by-step implementation approach -->

## Patterns to Follow

<!-- Reference .agent/workflows/ui-code-contracts.md §N or component-patterns.md §N -->

## Risks / Edge Cases

<!-- Anything that could go wrong or needs extra care -->

## Verification Plan

<!-- Commands to run after implementation to confirm correctness -->
\`\`\`bash
npx eslint <file> 2>&1 | grep "no-restricted-syntax"
\`\`\`
ANALYSIS

echo "Generated: ${ANALYSIS_FILE}"

# ── Generate todos.md scaffold ────────────────────────────────────────────────
TODOS_FILE="${WT_DIR}/${PLAN_DIR}/issue-${ISSUE}-todos.md"
cat > "$TODOS_FILE" <<TODOS
# Issue #${ISSUE} — Implementation TODOs

> To be completed by Claude before implementation begins.
> Approval required before any code changes start.

## Pre-flight

- [ ] Read \`.agent/workflows/ui-code-contracts.md\`
- [ ] Run self-verification baseline: \`npx eslint <file> 2>&1 | grep "no-restricted-syntax"\`

## Implementation Tasks

<!-- Granular, ordered checklist — one checkbox per logical change -->

- [ ]

## Verification

- [ ] ESLint: zero \`no-restricted-syntax\` violations on modified files
- [ ] No \`var(--\` aliases remain in modified files
- [ ] No \`onMouseEnter\`/\`onMouseLeave\` remain
- [ ] Light mode renders correctly
- [ ] Dark mode renders correctly
- [ ] Storybook story passes (if primitive)

## Commit Message

\`\`\`
fix(<scope>): <description> (closes #${ISSUE})

Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>
\`\`\`
TODOS

echo "Generated: ${TODOS_FILE}"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "============================================================"
echo "  Worktree ready. Review the plan files, then approve."
echo "============================================================"
echo ""
echo "  Spec:     ${SPEC_FILE}"
echo "  Analysis: ${ANALYSIS_FILE}"
echo "  TODOs:    ${TODOS_FILE}"
echo ""
echo "  cd ${WT_DIR} to begin work after approval."
echo "============================================================"
