#!/usr/bin/env bash
# =============================================================================
# scripts/mode-worktree-start.sh
# Create git worktrees for parallel mode-boundary development.
#
# Usage:
#   ./scripts/mode-worktree-start.sh --track <foundation|basic|pro|pro-xai>
#   ./scripts/mode-worktree-start.sh --all
#   ./scripts/mode-worktree-start.sh --list
#
# Worktrees live under .worktrees/ (gitignored).
# See docs/04-adrs/025-mode-feature-boundaries.md for the feature matrix.
# =============================================================================

set -euo pipefail

BASE="${BASE:-dev}"
TRACK=""
ALL=false
LIST=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --track) TRACK="$2"; shift 2 ;;
        --base)  BASE="$2";  shift 2 ;;
        --all)   ALL=true;   shift ;;
        --list)  LIST=true;  shift ;;
        -h|--help)
            sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *) echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
done

declare -A TRACK_BRANCH=(
    [foundation]="feature/mode-boundary-foundation"
    [basic]="feature/mode-boundary-basic"
    [pro]="feature/mode-boundary-pro"
    [pro-xai]="feature/mode-boundary-pro-xai"
)

declare -A TRACK_DIR=(
    [foundation]=".worktrees/wt-mode-foundation"
    [basic]=".worktrees/wt-mode-basic"
    [pro]=".worktrees/wt-mode-pro"
    [pro-xai]=".worktrees/wt-mode-pro-xai"
)

declare -A TRACK_SCOPE=(
    [foundation]="Shared canUseFeature() gate, useModeCapabilities hook, unit tests"
    [basic]="Basic-only UI: TTL, deny export/sync/tags/search/AI"
    [pro]="Pro gating: auth, sync, export, tags, search, LLMKeyStore tier, MCP export fix"
    [pro-xai]="10x-Pro AI: SubDomainView, LLM IPC, Settings AI providers, IAIMode decision"
)

if $LIST; then
    echo "Mode boundary worktrees:"
    for t in foundation basic pro pro-xai; do
        printf "  %-12s %s\n  %-12s branch: %s\n  %-12s scope: %s\n\n" \
            "$t" "${TRACK_DIR[$t]}" "" "${TRACK_BRANCH[$t]}" "" "${TRACK_SCOPE[$t]}"
    done
    git worktree list 2>/dev/null || true
    exit 0
fi

create_worktree() {
    local track="$1"
    local branch="${TRACK_BRANCH[$track]}"
    local wt_dir="${TRACK_DIR[$track]}"
    local plan_dir="${wt_dir}/docs/implementation-plans/mode-boundary"

    if git worktree list | grep -q "${branch}"; then
        echo "Worktree for '${branch}' already exists. Skipping."
        return 0
    fi

    echo "Creating worktree: ${wt_dir} (branch ${branch} from ${BASE})"
    git worktree add "$wt_dir" -b "$branch" "$BASE"

    mkdir -p "$plan_dir"

    cat > "${plan_dir}/${track}-plan.md" <<PLAN
# Mode Boundary Track: ${track}

> Auto-generated by \`scripts/mode-worktree-start.sh\`
> Branch: \`${branch}\`
> Worktree: \`${wt_dir}\`
> Base: \`${BASE}\`
> Date: $(date '+%Y-%m-%d')

## Scope

${TRACK_SCOPE[$track]}

## ADR

Read \`docs/04-adrs/025-mode-feature-boundaries.md\` before coding.

## Prerequisites

- Foundation track must merge before basic/pro/pro-xai if adding \`canUseFeature()\`.
- Each feature gate must check capability **and** runtime prerequisites (auth, vault unlock).

## Tasks

- [ ] Read ADR-025 feature matrix for this track
- [ ] Implement gates using \`canUseFeature()\` (not ad-hoc mode strings)
- [ ] Add/update unit tests for each gated surface
- [ ] Run \`npm run type-check && npm run build\`
- [ ] Manual verify per ADR-025 verification section

## Merge Order

foundation → basic → pro → pro-xai
PLAN

    echo "  Plan: ${plan_dir}/${track}-plan.md"
}

if $ALL; then
    for t in foundation basic pro pro-xai; do
        create_worktree "$t"
    done
elif [[ -n "$TRACK" ]]; then
    if [[ -z "${TRACK_BRANCH[$TRACK]:-}" ]]; then
        echo "ERROR: --track must be one of: foundation, basic, pro, pro-xai" >&2
        exit 1
    fi
    create_worktree "$TRACK"
else
    echo "ERROR: specify --track <name> or --all" >&2
    exit 1
fi

echo ""
echo "============================================================"
echo "  Mode boundary worktrees ready."
echo "  Run: ./scripts/mode-worktree-start.sh --list"
echo "============================================================"
git worktree list
