#!/usr/bin/env bash
# =============================================================================
# scripts/typography-worktree-start.sh
# Create git worktrees for parallel typography settings development.
#
# Usage:
#   ./scripts/typography-worktree-start.sh --track <foundation|import|ui>
#   ./scripts/typography-worktree-start.sh --all
#   ./scripts/typography-worktree-start.sh --list
#
# Worktrees live under .worktrees/ (gitignored).
# =============================================================================

set -euo pipefail

BASE="${BASE:-dev}"
TRACK=""
ALL=false
LIST=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --track) TRACK="$2"; shift 2 ;;
        --base)  BASE="$2";  shift 2 ;;
        --all)   ALL=true;   shift ;;
        --list)  LIST=true;  shift ;;
        -h|--help)
            sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *) echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
done

declare -A TRACK_BRANCH=(
    [foundation]="feature/typography-foundation"
    [import]="feature/typography-import"
    [ui]="feature/typography-ui"
)

declare -A TRACK_DIR=(
    [foundation]=".worktrees/wt-typography-foundation"
    [import]=".worktrees/wt-typography-import"
    [ui]=".worktrees/wt-typography-ui"
)

declare -A TRACK_SCOPE=(
    [foundation]="type-presets.ts (20 presets, tokens, migration), global.css vars, applyTypeTypography(), useTypePreset upgrade, TypePresetBootstrap, popup index.html cleanup, foundation tests"
    [import]="font-import-store.ts, validation, IndexedDB CRUD, @font-face injection wired into apply layer, import tests"
    [ui]="WheelPicker, CollapsibleSection, SectionValueColumns, EditableControlRow, TypographySettings rewrite, SettingsPage collapsible shell, UI tests"
)

if $LIST; then
    echo "Typography worktrees:"
    for t in foundation import ui; do
        printf "  %-12s %s\n  %-12s branch: %s\n  %-12s scope: %s\n\n" \
            "$t" "${TRACK_DIR[$t]}" "" "${TRACK_BRANCH[$t]}" "" "${TRACK_SCOPE[$t]}"
    done
    git worktree list 2>/dev/null || true
    exit 0
fi

create_worktree() {
    local track="$1"
    local branch="${TRACK_BRANCH[$track]}"
    local wt_dir="${TRACK_DIR[$track]}"
    local plan_dir="${wt_dir}/docs/implementation-plans/typography"

    if git worktree list | grep -q "${branch}"; then
        echo "Worktree for '${branch}' already exists. Skipping."
        return 0
    fi

    echo "Creating worktree: ${wt_dir} (branch ${branch} from ${BASE})"
    git worktree add "$wt_dir" -b "$branch" "$BASE"

    mkdir -p "$plan_dir"

    cat > "${plan_dir}/${track}-plan.md" <<PLAN
# Typography Track: ${track}

> Auto-generated by \`scripts/typography-worktree-start.sh\`
> Branch: \`${branch}\`
> Worktree: \`${wt_dir}\`
> Base: \`${BASE}\`
> Date: $(date '+%Y-%m-%d')

## Scope

${TRACK_SCOPE[$track]}

## UI spec

Canvas mock: typography-settings-mock.canvas.tsx

## Tasks

- [ ] Read typography implementation plan
- [ ] Implement track scope only
- [ ] Run \`npm run type-check && npm run build\`
- [ ] Open PR from \`${branch}\`

## Merge Order

foundation → import → ui (rebase downstream tracks after each merge)
PLAN

    echo "  Plan: ${plan_dir}/${track}-plan.md"
}

if $ALL; then
    for t in foundation import ui; do
        create_worktree "$t"
    done
elif [[ -n "$TRACK" ]]; then
    if [[ -z "${TRACK_BRANCH[$TRACK]:-}" ]]; then
        echo "ERROR: --track must be one of: foundation, import, ui" >&2
        exit 1
    fi
    create_worktree "$TRACK"
else
    echo "ERROR: specify --track <name> or --all" >&2
    exit 1
fi

echo ""
echo "============================================================"
echo "  Typography worktrees ready."
echo "  Run: ./scripts/typography-worktree-start.sh --list"
echo "============================================================"
git worktree list
